cargo-features = ["edition2021"]
[package]
name = "rust-misc"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web="0.7"
env_logger="0.6"
serde={version = "1.0", features=["derive"]}
serde_json = "1.0"
